# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "${REDIS_DB_PORT}:${REDIS_DB_PORT}"
      - "${REDIS_INSIGHTS_PORT}:${REDIS_INSIGHTS_PORT}"
  whisper-service:
    image: ${REGISTRY:-opea}/whisper:${TAG:-latest}
    container_name: whisper-service
    ports:
      - "${WHISPER_PORT}:${WHISPER_PORT}"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
  asr:
    image: ${REGISTRY:-opea}/asr:${TAG:-latest}
    container_name: asr-service
    ports:
      - "${ASR_SERVICE_PORT}:${ASR_PORT}"
    ipc: host
    environment:
      ASR_ENDPOINT: ${ASR_ENDPOINT}
      ASR_SERVICE_PORT: ${ASR_SERVICE_PORT}
      ASR_SERVICE_ENDPOINT: ${ASR_SERVICE_ENDPOINT}
  dataprep-multimodal-redis:
    image: ${REGISTRY:-opea}/dataprep-multimodal-redis:${TAG:-latest}
    container_name: dataprep-multimodal-redis
    depends_on:
      - redis-vector-db
      - lvm-tgi
    ports:
      - "${DATAPREP_MMR_PORT}:${DATAPREP_MMR_PORT}"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${REDIS_HOST}
      INDEX_NAME: ${INDEX_NAME}
      LVM_ENDPOINT: "http://${LVM_SERVICE_HOST_IP}:${LVM_PORT}/v1/lvm"
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  embedding-multimodal-bridgetower:
    image: ${REGISTRY:-opea}/embedding-multimodal-bridgetower:${TAG:-latest}
    container_name: embedding-multimodal-bridgetower
    ports:
      - ${EMM_BRIDGETOWER_PORT}:${EMM_BRIDGETOWER_PORT}
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      PORT: ${EMM_BRIDGETOWER_PORT}
    entrypoint: ["python", "bridgetower_server.py", "--device", "hpu", "--model_name_or_path", $EMBEDDING_MODEL_ID]
    restart: unless-stopped
  embedding-multimodal:
    image: ${REGISTRY:-opea}/embedding-multimodal:${TAG:-latest}
    container_name: embedding-multimodal
    depends_on:
      - embedding-multimodal-bridgetower
    ports:
      - ${MM_EMBEDDING_PORT_MICROSERVICE}:${MM_EMBEDDING_PORT_MICROSERVICE}
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MMEI_EMBEDDING_ENDPOINT: ${MMEI_EMBEDDING_ENDPOINT}
      MM_EMBEDDING_PORT_MICROSERVICE: ${MM_EMBEDDING_PORT_MICROSERVICE}
    restart: unless-stopped
  retriever-multimodal-redis:
    image: ${REGISTRY:-opea}/retriever-multimodal-redis:${TAG:-latest}
    container_name: retriever-multimodal-redis
    depends_on:
      - redis-vector-db
    ports:
      - "${REDIS_RETREIEVER_PORT}:${REDIS_RETREIEVER_PORT}"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
    restart: unless-stopped
  tgi-gaudi:
    image: ghcr.io/huggingface/tgi-gaudi:2.0.6
    container_name: tgi-llava-gaudi-server
    ports:
      - ${TGI_GAUDI_PORT}
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      PREFILL_BATCH_BUCKET_SIZE: 1
      BATCH_BUCKET_SIZE: 1
      MAX_BATCH_TOTAL_TOKENS: 4096
      ENABLE_HPU_GRAPH: true
      LIMIT_HPU_GRAPH: true
      USE_FLASH_ATTENTION: true
      FLASH_ATTENTION_RECOMPUTE: true
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    command: --model-id ${LVM_MODEL_ID} --max-input-tokens 3048 --max-total-tokens 4096
    restart: unless-stopped
  lvm-tgi:
    image: ${REGISTRY:-opea}/lvm-tgi:${TAG:-latest}
    container_name: lvm-tgi
    depends_on:
      - tgi-gaudi
    ports:
      - "${LVM_PORT}:${LVM_PORT}"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LVM_ENDPOINT: ${LVM_ENDPOINT}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      MAX_IMAGES: ${MAX_IMAGES:-1}
    restart: unless-stopped
  multimodalqna:
    image: ${REGISTRY:-opea}/multimodalqna:${TAG:-latest}
    container_name: multimodalqna-backend-server
    depends_on:
      - redis-vector-db
      - dataprep-multimodal-redis
      - embedding-multimodal
      - retriever-multimodal-redis
      - lvm-tgi
      - asr
    ports:
      - "${MEGASERVICE_PORT}:${MEGASERVICE_PORT}"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      MEGA_SERVICE_HOST_IP: ${MEGA_SERVICE_HOST_IP}
      MM_EMBEDDING_SERVICE_HOST_IP: ${MM_EMBEDDING_SERVICE_HOST_IP}
      MM_EMBEDDING_PORT_MICROSERVICE: ${MM_EMBEDDING_PORT_MICROSERVICE}
      MM_RETRIEVER_SERVICE_HOST_IP: ${MM_RETRIEVER_SERVICE_HOST_IP}
      LVM_SERVICE_HOST_IP: ${LVM_SERVICE_HOST_IP}
      LVM_MODEL_ID: ${LVM_MODEL_ID}
      ASR_SERVICE_PORT: ${ASR_SERVICE_PORT}
      ASR_SERVICE_ENDPOINT: ${ASR_SERVICE_ENDPOINT}
    ipc: host
    restart: always
  multimodalqna-ui:
    image: ${REGISTRY:-opea}/multimodalqna-ui:${TAG:-latest}
    container_name: multimodalqna-gradio-ui-server
    depends_on:
      - multimodalqna
    ports:
      - "${UI_PORT}:${UI_PORT}"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BACKEND_SERVICE_ENDPOINT=${BACKEND_SERVICE_ENDPOINT}
      - DATAPREP_INGEST_SERVICE_ENDPOINT=${DATAPREP_INGEST_SERVICE_ENDPOINT}
      - DATAPREP_GEN_TRANSCRIPT_SERVICE_ENDPOINT=${DATAPREP_GEN_TRANSCRIPT_SERVICE_ENDPOINT}
      - DATAPREP_GEN_CAPTION_SERVICE_ENDPOINT=${DATAPREP_GEN_CAPTION_SERVICE_ENDPOINT}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
